Repository ChetnaNSharma/Alumni-Connect, pull requests merged in 2021-05, with the labels that each got.

#100 Create chatbot
  alumni-connect/package.json
  alumni-connect/src/App.js
  alumni-connect/src/Components/ChatBot/ChatBot.css
  alumni-connect/src/Components/ChatBot/ChatBot.js
  alumni-connect/src/Components/ChatBot/Simpleform.js
  alumni-connect/yarn.lock
Labels: Difficult, GSSoC'21, GSSoC21, Level3, Moderate, enhancement, help wanted

#121 sound in chatbot
  alumni-connect/src/Components/ChatBot/Simpleform.js
Labels: GSSoC'21, GSSoC21, Level2, Moderate, enhancement, help wanted

#152 splash screen
  alumni-connect/src/Components/Preloader/Preloader.css
  alumni-connect/src/Components/Preloader/Preloader.js
Labels: GSSoC'21, GSSoC21, enhancement

#154 signup
  alumni-connect/src/Components/Pages/Signup/signup.css
  alumni-connect/src/Components/Pages/Signup/signup.js
Labels: Difficult, GSSoC'21, GSSoC21, Level3, Moderate, enhancement, help wanted
